export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-ground text-ink px-4 py-10">
      <div className="max-w-2xl mx-auto space-y-6">
        <a href="/" className="text-sm text-ink-dim underline underline-offset-2">
          ← Back
        </a>
        <h1 className="text-2xl font-bold">Privacy Policy</h1>
        <p className="text-xs text-ink-faint">Last updated: September 2026</p>

        <section className="space-y-2 text-sm text-ink-dim leading-relaxed">
          <h2 className="text-base font-semibold text-ink">What we collect</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>
              <strong className="text-ink">Account info:</strong> your email
              address, used for magic-link sign-in.
            </li>
            <li>
              <strong className="text-ink">Meals:</strong> photos you upload,
              notes, and the nutrition estimates you save.
            </li>
            <li>
              <strong className="text-ink">Profile &amp; goals:</strong> weight,
              height, age, activity level, display name, and macro targets you
              set — used to personalize your dashboard.
            </li>
            <li>
              <strong className="text-ink">Shares:</strong> recipient email
              addresses and messages when you share a meal.
            </li>
          </ul>
        </section>

        <section className="space-y-2 text-sm text-ink-dim leading-relaxed">
          <h2 className="text-base font-semibold text-ink">
            How AI processes your data
          </h2>
          <p>
            When you log a meal, your photo or description is sent to our AI
            providers (Anthropic and Google) solely to estimate nutrition
            information. We do not use your meals to train AI models, and we
            do not sell your data.
          </p>
        </section>

        <section className="space-y-2 text-sm text-ink-dim leading-relaxed">
          <h2 className="text-base font-semibold text-ink">Third parties</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>
              <strong className="text-ink">Supabase</strong> — database,
              authentication, and photo storage.
            </li>
            <li>
              <strong className="text-ink">Resend</strong> — sends sign-in and
              meal-share emails.
            </li>
            <li>
              <strong className="text-ink">Unsplash</strong> — stock food
              imagery shown for text-logged meals.
            </li>
          </ul>
        </section>

        <section className="space-y-2 text-sm text-ink-dim leading-relaxed">
          <h2 className="text-base font-semibold text-ink">Your rights</h2>
          <p>
            You can delete individual meals anytime from the app. To export or
            permanently delete your entire account and all associated data,
            email us and we will complete the request within 30 days.
          </p>
        </section>

        <section className="space-y-2 text-sm text-ink-dim leading-relaxed">
          <h2 className="text-base font-semibold text-ink">
            Not medical advice
          </h2>
          <p>
            Nutrition estimates are generated by AI and are approximate. This
            app is not a medical device and does not provide medical advice.
            Consult a qualified professional for dietary or health decisions.
          </p>
        </section>
      </div>
    </div>
  )
}
